/**
 * Party Management Micro Service
 * This service is the party manager
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.partymanagement.client.model




sealed trait PartyRoleEnum

case object MANAGER extends PartyRoleEnum
case object DELEGATE extends PartyRoleEnum
case object OPERATOR extends PartyRoleEnum


object PartyRoleEnum {
    def fromValue(value: String): Either[Throwable, PartyRoleEnum] =
      value match {
         case "MANAGER" => Right(MANAGER)
         case "DELEGATE" => Right(DELEGATE)
         case "OPERATOR" => Right(OPERATOR)
         case other => Left(new RuntimeException(s"Unable to decode value $other"))
      }
}
