/**
 * Party Management Micro Service
 * This service is the party manager
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.partymanagement.client.model




sealed trait RelationshipStatusEnum

case object PENDING extends RelationshipStatusEnum
case object ACTIVE extends RelationshipStatusEnum
case object SUSPENDED extends RelationshipStatusEnum
case object DELETED extends RelationshipStatusEnum
case object REJECTED extends RelationshipStatusEnum


object RelationshipStatusEnum {
    def fromValue(value: String): Either[Throwable, RelationshipStatusEnum] =
      value match {
         case "PENDING" => Right(PENDING)
         case "ACTIVE" => Right(ACTIVE)
         case "SUSPENDED" => Right(SUSPENDED)
         case "DELETED" => Right(DELETED)
         case "REJECTED" => Right(REJECTED)
         case other => Left(new RuntimeException(s"Unable to decode value $other"))
      }
}
