/**
 * Party Management Micro Service
 * This service is the party manager
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.partymanagement.client.model




sealed trait RelationshipStatusEnum

case object PENDING extends RelationshipStatusEnum
case object ACTIVE extends RelationshipStatusEnum
case object SUSPENDED extends RelationshipStatusEnum
case object DELETED extends RelationshipStatusEnum
case object REJECTED extends RelationshipStatusEnum

