version: '3.0'
services:
  postgres:
    image: postgres:10.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: party_management_persistence
      POSTGRES_PASSWORD: password
