/**
 * Party Management Micro Service
 * This service is the party manager
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.partymanagement.client.api

import it.pagopa.pdnd.interop.uservice.partymanagement.client.model.Problem
import it.pagopa.pdnd.interop.uservice.partymanagement.client.invoker._
import it.pagopa.pdnd.interop.uservice.partymanagement.client.invoker.CollectionFormats._
import it.pagopa.pdnd.interop.uservice.partymanagement.client.invoker.ApiKeyLocations._

object HealthApi {

  def apply(baseUrl: String = "http://localhost/pdnd-interop-uservice-party-management/}") = new HealthApi(baseUrl)
}

class HealthApi(baseUrl: String) {

  /**
   * Return ok
   * 
   * Expected answers:
   *   code 200 : Problem (successful operation)
   */
  def getStatus(): ApiRequest[Problem] =
    ApiRequest[Problem](ApiMethods.GET, baseUrl, "/status", "application/json")
      .withSuccessResponse[Problem](200)
      



}

