object Versions {
  lazy val akkaVersion              = "2.6.15"
  lazy val akkaCassandraVersion     = "1.0.5"
  lazy val akkaPersistenceS3Version = "1.1.41"
  lazy val projectionVersion        = "1.2.1"
  lazy val akkaHttpVersion          = "10.2.4"
  lazy val akkaManagementVersion    = "1.1.1"
  lazy val httpJson4sVersion        = "1.37.0"
  lazy val catsVersion              = "2.6.1"
  lazy val json4sVersion            = "4.0.1"
  lazy val openapi4jVersion         = "1.0.7"
  lazy val kamonVersion             = "2.2.2"
  lazy val logbackVersion           = "1.2.4"
  lazy val scalatestVersion         = "3.2.9"
  lazy val mockitoVersion           = "3.7.7"
  lazy val scalaMockVersion         = "5.1.0"
  lazy val stateMonitoringVersion   = "0.0.3-SNAPSHOT"
}
