name: Scala CI

on:
  push:
    branches: [ test-deploy ]
env:
  DOCKER_REPO: ghcr.io
  OWNER: pagopa
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: docker_login
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login $DOCKER_REPO -u ${{ github.actor }} --password-stdin
    - name: Compile
      run: sbt clean generateCode compile
    - name: Test
      run: sbt test
    - name: Test
      run: sbt docker:publish
